---
name: push to kaggle

on:
  push:
    paths:
      - ".github/workflows/push-to-kaggle.yml"
      - "requirements-dataset.txt"
  schedule: # Schedule the workflow to run every day at midnight
  - cron: "0 0 * * *"

jobs:
  create-and-upload-dataset:
    name: push to kaggle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install python 3.7.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.12' 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Kaggle login
        uses: osbm/kaggle-login@v2.1
        with:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

        
      - name: Download wheels
        run: |
          pip wheel -r requirements-dataset.txt -w ./dataset/  

      - name: Upload dataset to kaggle
        run: |
          kaggle datasets version -p ./dataset/ -m "Updating wheels" 
